import { ColorRule, DayOfWeekKey } from '../src/types';

export const SEED_COLOR_RULES: ColorRule[] = [
  // --- วันอาทิตย์ (Sunday) ---
  {
    id: 'rule-sun-1',
    dayOfWeek: 'sunday',
    colorName: 'แดงทับทิม',
    hexCode: '#DC2626',
    type: 'recommended',
    priority: 1,
    description: 'สีเสริมพลังอำนาจบารมี และความมั่นใจ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sun-2',
    dayOfWeek: 'sunday',
    colorName: 'เขียวมรกต',
    hexCode: '#059669',
    type: 'recommended',
    priority: 2,
    description: 'สีส่งเสริมโชคลาภการเงินและทรัพย์สิน',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sun-3',
    dayOfWeek: 'sunday',
    colorName: 'ชมพูกลีบบัว',
    hexCode: '#F472B6',
    type: 'secondary',
    priority: 3,
    description: 'สีเสริมเสน่ห์และความเมตตามหานิยม',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sun-4',
    dayOfWeek: 'sunday',
    colorName: 'ขาวมุก',
    hexCode: '#F8FAFC',
    type: 'secondary',
    priority: 4,
    description: 'สีโทนสุภาพ เสริมความราบรื่นในหน้าที่การงาน',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sun-5',
    dayOfWeek: 'sunday',
    colorName: 'น้ำเงินกรมท่า',
    hexCode: '#1E3A8A',
    type: 'kali',
    priority: 10,
    description: 'สีกาลกิณีประจำวันอาทิตย์ตามตำรา ควรหลีกเลี่ยง',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sun-6',
    dayOfWeek: 'sunday',
    colorName: 'ฟ้าคราม',
    hexCode: '#38BDF8',
    type: 'avoid',
    priority: 9,
    description: 'สีที่ควรเลี่ยงในวันอาทิตย์เพื่อความคล่องตัว',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- วันจันทร์ (Monday) ---
  {
    id: 'rule-mon-1',
    dayOfWeek: 'monday',
    colorName: 'เหลืองนวล',
    hexCode: '#FBBF24',
    type: 'recommended',
    priority: 1,
    description: 'สีประจำวันจันทร์ เสริมสง่าราศีและความสุข',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-mon-2',
    dayOfWeek: 'monday',
    colorName: 'ม่วงลาเวนเดอร์',
    hexCode: '#8B5CF6',
    type: 'recommended',
    priority: 2,
    description: 'สีเสริมทรัพย์สิน เงินทอง ความสำเร็จทางธุรกิจ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-mon-3',
    dayOfWeek: 'monday',
    colorName: 'เขียวมิ้นต์',
    hexCode: '#34D399',
    type: 'secondary',
    priority: 3,
    description: 'สีช่วยหนุนนำเรื่องผู้ใหญ่เอ็นดูและผู้อุปถัมภ์',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-mon-4',
    dayOfWeek: 'monday',
    colorName: 'ส้มอิฐ',
    hexCode: '#EA580C',
    type: 'secondary',
    priority: 4,
    description: 'สีช่วยเสริมความมุ่งมั่นและความคิดสร้างสรรค์',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-mon-5',
    dayOfWeek: 'monday',
    colorName: 'แดงสด',
    hexCode: '#EF4444',
    type: 'kali',
    priority: 10,
    description: 'สีกาลกิณีสำหรับคนเกิดวันจันทร์ ระบบจะตัดออกอัตโนมัติ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-mon-6',
    dayOfWeek: 'monday',
    colorName: 'แดงเลือดหมู',
    hexCode: '#991B1B',
    type: 'avoid',
    priority: 9,
    description: 'สีโทนแดงเข้มควรหลีกเลี่ยงในวันจันทร์',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- วันอังคาร (Tuesday) ---
  {
    id: 'rule-tue-1',
    dayOfWeek: 'tuesday',
    colorName: 'ชมพูกลีบบัว',
    hexCode: '#EC4899',
    type: 'recommended',
    priority: 1,
    description: 'สีประจำวันอังคาร เสริมพลังความสดใสและมิตรภาพ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-tue-2',
    dayOfWeek: 'tuesday',
    colorName: 'ส้มแสด',
    hexCode: '#F97316',
    type: 'recommended',
    priority: 2,
    description: 'สีเสริมโชคลาภเงินทองและความก้าวหน้า',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-tue-3',
    dayOfWeek: 'tuesday',
    colorName: 'ดำคาร์บอน',
    hexCode: '#18181B',
    type: 'secondary',
    priority: 3,
    description: 'สีเสริมความน่าเชื่อถือและความเด็ดขาด',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-tue-4',
    dayOfWeek: 'tuesday',
    colorName: 'ม่วงเข้ม',
    hexCode: '#7C3AED',
    type: 'secondary',
    priority: 4,
    description: 'สีแห่งเสน่ห์ดึงดูดใจและความสง่างาม',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-tue-5',
    dayOfWeek: 'tuesday',
    colorName: 'ขาวบริสุทธิ์',
    hexCode: '#FFFFFF',
    type: 'kali',
    priority: 10,
    description: 'สีกาลกิณีสำหรับคนเกิดวันอังคาร ควรหลีกเลี่ยง',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-tue-6',
    dayOfWeek: 'tuesday',
    colorName: 'เหลืองอ่อน',
    hexCode: '#FEF08A',
    type: 'avoid',
    priority: 9,
    description: 'สีโทนเหลืองครีมควรเลี่ยงสำหรับวันอังคาร',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- วันพุธ กลางวัน (Wednesday Day) ---
  {
    id: 'rule-wed-d-1',
    dayOfWeek: 'wednesday_day',
    colorName: 'เขียวใบตอง',
    hexCode: '#10B981',
    type: 'recommended',
    priority: 1,
    description: 'สีประจำวันพุธกลางวัน เสริมการเจรจาและการสื่อสาร',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-wed-d-2',
    dayOfWeek: 'wednesday_day',
    colorName: 'น้ำเงินคราม',
    hexCode: '#2563EB',
    type: 'recommended',
    priority: 2,
    description: 'สีหนุนโชคลาภการเงินและความรุ่งเรือง',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-wed-d-3',
    dayOfWeek: 'wednesday_day',
    colorName: 'เทาสโมค',
    hexCode: '#64748B',
    type: 'secondary',
    priority: 3,
    description: 'สีเสริมความสุขุมและรอบคอบในการทำงาน',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-wed-d-4',
    dayOfWeek: 'wednesday_day',
    colorName: 'ทองแชมเปญ',
    hexCode: '#D4AF37',
    type: 'secondary',
    priority: 4,
    description: 'สีนำพาความหรูหราและความมั่งคั่ง',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-wed-d-5',
    dayOfWeek: 'wednesday_day',
    colorName: 'ชมพูบานเย็น',
    hexCode: '#DB2777',
    type: 'kali',
    priority: 10,
    description: 'สีกาลกิณีวันพุธกลางวัน จะถูกตัดออกจากระบบ Color Match',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-wed-d-6',
    dayOfWeek: 'wednesday_day',
    colorName: 'ชมพูพาสเทล',
    hexCode: '#FBCFE8',
    type: 'avoid',
    priority: 9,
    description: 'สีโทนชมพูควรหลีกเลี่ยงในวันพุธกลางวัน',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- วันพุธ กลางคืน / พระราหู (Wednesday Night) ---
  {
    id: 'rule-wed-n-1',
    dayOfWeek: 'wednesday_night',
    colorName: 'เทาดำเมทัลลิก',
    hexCode: '#334155',
    type: 'recommended',
    priority: 1,
    description: 'สีเสริมบารมี พลังอำนาจและความเด็ดขาด',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-wed-n-2',
    dayOfWeek: 'wednesday_night',
    colorName: 'ขาวมุกนวล',
    hexCode: '#F1F5F9',
    type: 'recommended',
    priority: 2,
    description: 'สีนำพาโชคลาภการเงินและโอกาสใหม่ ๆ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-wed-n-3',
    dayOfWeek: 'wednesday_night',
    colorName: 'ฟ้าเทอร์ควอยซ์',
    hexCode: '#06B6D4',
    type: 'secondary',
    priority: 3,
    description: 'สีเสริมจินตนาการและการแก้ไขปัญหาเฉพาะหน้า',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-wed-n-4',
    dayOfWeek: 'wednesday_night',
    colorName: 'ส้มคอรัล',
    hexCode: '#FB923C',
    type: 'kali',
    priority: 10,
    description: 'สีกาลกิณีวันพุธกลางคืน ควรหลีกเลี่ยง',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- วันพฤหัสบดี (Thursday) ---
  {
    id: 'rule-thu-1',
    dayOfWeek: 'thursday',
    colorName: 'ส้มอิฐอบอุ่น',
    hexCode: '#EA580C',
    type: 'recommended',
    priority: 1,
    description: 'สีประจำวันพฤหัสบดี เสริมปัญญา ความก้าวหน้าทางการศึกษาและการงาน',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-thu-2',
    dayOfWeek: 'thursday',
    colorName: 'แดงเบอร์กันดี',
    hexCode: '#B91C1C',
    type: 'recommended',
    priority: 2,
    description: 'สีเสริมโชคลาภ ทรัพย์สิน ความมั่งคั่ง',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-thu-3',
    dayOfWeek: 'thursday',
    colorName: 'ฟ้าครามสว่าง',
    hexCode: '#0284C7',
    type: 'secondary',
    priority: 3,
    description: 'สีเสริมความเมตตาและคนคอยช่วยเหลือ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-thu-4',
    dayOfWeek: 'thursday',
    colorName: 'เขียวมะกอก',
    hexCode: '#65A30D',
    type: 'secondary',
    priority: 4,
    description: 'สีแห่งความมั่นคงและสุขภาพดี',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-thu-5',
    dayOfWeek: 'thursday',
    colorName: 'ดำสนิท',
    hexCode: '#09090B',
    type: 'kali',
    priority: 10,
    description: 'สีกาลกิณีวันพฤหัสบดี ระบบจะคัดกรองออก 100%',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-thu-6',
    dayOfWeek: 'thursday',
    colorName: 'ม่วงเข้มมืด',
    hexCode: '#581C87',
    type: 'avoid',
    priority: 9,
    description: 'สีโทนมืดสนิทควรเลี่ยงสำหรับวันพฤหัสบดี',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- วันศุกร์ (Friday) ---
  {
    id: 'rule-fri-1',
    dayOfWeek: 'friday',
    colorName: 'ฟ้าสกายบลู',
    hexCode: '#0284C7',
    type: 'recommended',
    priority: 1,
    description: 'สีประจำวันศุกร์ เสริมความสุข ความสดชื่น และความรัก',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-fri-2',
    dayOfWeek: 'friday',
    colorName: 'ชมพูพาสเทล',
    hexCode: '#F472B6',
    type: 'recommended',
    priority: 2,
    description: 'สีเสริมความร่ำรวย โชคลาภและการเงิน',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-fri-3',
    dayOfWeek: 'friday',
    colorName: 'ขาวมุกประกาย',
    hexCode: '#F8FAFC',
    type: 'secondary',
    priority: 3,
    description: 'สีหนุนพลังแห่งความบริสุทธิ์และมิตรภาพที่จริงใจ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-fri-4',
    dayOfWeek: 'friday',
    colorName: 'เขียวแอปเปิ้ล',
    hexCode: '#22C55E',
    type: 'secondary',
    priority: 4,
    description: 'สีเสริมสุขภาพและชีวิตชีวา',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-fri-5',
    dayOfWeek: 'friday',
    colorName: 'ดำชาร์โคล',
    hexCode: '#1E293B',
    type: 'kali',
    priority: 10,
    description: 'สีกาลกิณีประจำวันศุกร์ ควรหลีกเลี่ยงอย่างยิ่ง',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-fri-6',
    dayOfWeek: 'friday',
    colorName: 'เทาดำเข้ม',
    hexCode: '#374151',
    type: 'avoid',
    priority: 9,
    description: 'สีโทนมืดหม่นควรเลี่ยงในวันศุกร์',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- วันเสาร์ (Saturday) ---
  {
    id: 'rule-sat-1',
    dayOfWeek: 'saturday',
    colorName: 'ม่วงไวโอเล็ต',
    hexCode: '#7C3AED',
    type: 'recommended',
    priority: 1,
    description: 'สีประจำวันเสาร์ เสริมเสน่ห์ ความลึกลับน่าค้นหา และอำนาจ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sat-2',
    dayOfWeek: 'saturday',
    colorName: 'ฟ้าครามทะเล',
    hexCode: '#0EA5E9',
    type: 'recommended',
    priority: 2,
    description: 'สีเสริมโชคลาภ การเงิน และความมั่งคั่ง',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sat-3',
    dayOfWeek: 'saturday',
    colorName: 'ดำคลาสสิก',
    hexCode: '#111827',
    type: 'secondary',
    priority: 3,
    description: 'สีเสริมความน่าเกรงขามและความเป็นผู้นำ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sat-4',
    dayOfWeek: 'saturday',
    colorName: 'แดงเข้มทับทิม',
    hexCode: '#BE123C',
    type: 'secondary',
    priority: 4,
    description: 'สีเสริมความมั่นใจและการตัดสินใจที่แม่นยำ',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sat-5',
    dayOfWeek: 'saturday',
    colorName: 'เขียวสด',
    hexCode: '#16A34A',
    type: 'kali',
    priority: 10,
    description: 'สีกาลกิณีวันเสาร์ ระบบจะตัดออกจากชุดทั้งหมด',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rule-sat-6',
    dayOfWeek: 'saturday',
    colorName: 'เขียวตองอ่อน',
    hexCode: '#84CC16',
    type: 'avoid',
    priority: 9,
    description: 'สีโทนเขียวสว่างควรหลีกเลี่ยงสำหรับวันเสาร์',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
